import tkinter

master_window = tkinter.Tk()

#Menu
menu1= tkinter.Menu(master_window)
master_window.config(menu=menu1)
filemenu = tkinter.Menu(menu1, tearoff=0)
menu1.add_cascade(label="file", menu=filemenu)
filemenu.add_command(label="New Text File")
filemenu.add_command(label="New File...")
filemenu.add_command(label="New Window")
filemenu.add_command(label= "New Window with Profile")
filemenu.add_separator()
filemenu.add_command(label="Open file...")
filemenu.add_command(label="Open folder...")
filemenu.add_command(label="Open Workspace from File...")
filemenu.add_command(label="Open Recent")
filemenu.add_separator()
filemenu.add_command(label="Add Folder to Workspace...")
filemenu.add_command(label="Save Workspace As...")
filemenu.add_command(label="Duplicate Workspace")
filemenu.add_separator()
filemenu.add_command(label="Save")
filemenu.add_command(label="Save As...")
filemenu.add_command(label="Save All")
filemenu.add_separator()
filemenu.add_command(label="Share")
filemenu.add_separator()
filemenu.add_command(label="Auto Save")
filemenu.add_command(label="Preferences")
filemenu.add_separator()
filemenu.add_command(label="Revert File")
filemenu.add_command(label="Close Editor")
filemenu.add_command(label="Close Folder")
filemenu.add_command(label="Close Window")
filemenu.add_separator()
filemenu.add_command(label="Exit", command=master_window.destroy)


#Edit menu
edit = tkinter.Menu(menu1, tearoff=0)
menu1.add_cascade(label="Edit", menu=edit)
edit.add_command(label="Undo")
edit.add_command(label="Redo")
edit.add_separator()
edit.add_command(label="Cut")
edit.add_command(label="Copy")
edit.add_command(label="Paste")
edit.add_separator()
edit.add_command(label="Find")
edit.add_command(label="Replace")
edit.add_separator()
edit.add_command(label="Find in Files")
edit.add_command(label="Replace in Files")
edit.add_separator()
edit.add_command(label="Toggle Line Comment")
edit.add_command(label="Toggle Block Comment")
edit.add_command(label="Emmet: Expand Abbreviation")
edit.add_separator()




master_window.mainloop()
